name: ci #it could be any name. The goal is to assign a human-readable name

on: #the 'on' key specifies when the workflow should run
  pull_request: #in this case, the workflow should run when a PR is open to the main branch
    branches: [main]

jobs: # a workflow is made of one or more jobs. A job is a set of steps that run of the same runner (a VM that runs the job on GitHub's servers)
  tests: # this is a "job ID" chosen by the author. It could be any word.
    name: Tests #it could be any name. The goal is to assign a human-readable name
    runs-on: ubuntu-latest #the 'runs-on' key specifies the type of runner that should be used

    steps:
      - name: Check out code
        uses: actions/checkout@v4 #this is a pre-built checkout of GitHub to clone the repository into the runner

      - name: Set up Go
        uses: actions/setup-go@v5 #this sets up Go using a pre-built setup-go action (it configures a Go environment for use in workflows)
        with:
          go-version: "1.26.3"

      #- name: Check Go version
      #  run: go version #the 'run' key is used to run arbitrary command-line commands in the runner.

      # while the 'uses' key refers to an external pre-defined GitHub action, the 'run' key refers to a custom command.

      - name: Run tests
        run: go test ./... -cover

  style: # this is a "job ID" chosen by the author. It could be any word.
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 #this is a pre-built checkout of GitHub to clone the repository into the runner

      - name: Set up Go
        uses: actions/setup-go@v5 #this sets up Go using a pre-built setup-go action (it configures a Go environment for use in workflows)
        with:
          go-version: "1.26.3"
      
      - name: Check formatting
        run: test -z $(go fmt ./...)
        #the $() syntax is used for command substitution in bash. It runs the command inside the parentheses, and then replaces the $() in the command line with the output of that command.
        #the test command is built into bash. The -z option checks if the following argument is an empty string, returning 0 if it is, and 1 if it isn't.
